export const SIGN_UP_WITH_GOOGLE = 'SIGN_UP_WITH_GOOGLE';
export const SIGN_IN_WITH_GOOGLE = 'SIGN_IN_WITH_GOOGLE';

export const SIGN_UP_WITH_EMAIL_AND_PASSWORD = 'SIGN_UP_WITH_EMAIL_AND_PASSWORD';
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD = 'SIGN_IN_WITH_EMAIL_AND_PASSWORD';

export const SET_USER = 'SET_USER';
export const DELETE_USER = 'DELETE_USER';

export const SIGN_OUT = 'SIGN_OUT';

