export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
export const SHOW_ALL_CATEGORIES = 'SHOW_ALL_CATEGORIES';