export const GET_TASKS = 'GET_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SELECT_TASK = 'SELECT_TASK';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const DELETE_COMPLETED_TASKS = 'DELETE_COMPLETED_TASKS';
export const DELETE_OUTDATED_TASKS = 'DELETE_OUTDATED_TASKS';