export const MAIN = 'MAIN';

export const USER = 'USER';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const COLOR = 'COLOR';

export const TODOLIST = 'TODOLIST';
export const CHANGE_TODOLIST_VIEWER = 'CHANGE_TODOLIST_VIEWER';
export const DELETE_COMPLETED_TASKS = 'DELETE_COMPLETED_TASKS';
export const DELETE_OUTDATED_TASKS = 'DELETE_OUTDATED_TASKS';